# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: qqplot
google_analytics: 'G-JF12SRF3ZB'
title: qqplot

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: qqplot

description: qqplot's blog
author:
  name: qqplot
  email: kyubyung91@gmail.com
  github: qqplot
  # twitter: dbtek
  resume: da0fd52be931436d9f593bf0b50549c8
  linkedin: qqplot
  bio: Your stylish, minimalist theme!
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
sidebar_background_image: https://github.com/qqplot/qqplot.github.io/blob/main/assets/images/lighthouse-5354475_1280.jpg?raw=true

BASE_PATH:

plugins:
  - jekyll-paginate
