# Site
name: "qqplot"
title: "qqplot"
description: "qqplot의 기술블로그"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
url: 'https://qqplot.github.io/'
google_analytics: 'G-JF12SRF3ZB'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: kyubyung91@gmail.com

# Authors
authors:
  qqplot:
    name: qqplot
    display_name: qqplot
    avatar: 'assets/images/avatar.png'
    email: kyubyung91@gmail.com
    web: https://pentagonal-bow-0d6.notion.site/CV_kyubyung-da0fd52be931436d9f593bf0b50549c8
    description: "Data Scientist"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
rouge: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "ca-pub-2356506376607392"
adsense-data-ad-slot: "9552563134"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
